/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technicalservicesoftware;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author Gizem
 */
public class BelliTarihteGelirGiderKarZararDokumu extends javax.swing.JFrame {
    private Connection baglanti;
    private ResultSet sonuc;
    private Statement ifade;
    private DatabaseAccessObject dao=new DatabaseAccessObject();
    /**
     * Creates new form BelliTarihteGelirGiderKarZararDokumu
     */
    public BelliTarihteGelirGiderKarZararDokumu() {
        initComponents();
    }
    private double OnTanimliIsGelir(String BasTarih,String BitTarih){       
      String sql="SELECT satildigi_ucret FROM \"YapilanOnTanimliIsler\" where tarih between '"+BasTarih+"' and '"+BitTarih+"'";
      double toplam=0;
      int row;
      try {
          sonuc=ifade.executeQuery(sql);
          sonuc.last();
          row=sonuc.getRow();
          sonuc.first();
          
          for(int i=0;i<row;i++){
                toplam+=sonuc.getDouble("satildigi_ucret");
                sonuc.next();
            }

      } catch (Exception e) {
         
      } 
      return toplam;
    }
    private int MalzemeGelisFiyati(int malzeme_id){
        String sql="SELECT * FROM \"Malzeme\""; 
        int fiyat=0;
         try {
          baglanti=dao.getBaglanti();
          ifade=baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
          sonuc=ifade.executeQuery(sql);
          while(sonuc.next()){
                if(sonuc.getInt("malzeme_id")==malzeme_id){
                    //System.out.println(sonuc.getInt("malzeme_id"));
                    return sonuc.getInt("malzeme_gelis_fiyati");
                } 
            }
          
         } 
         catch (Exception e) {
          
         }
        return fiyat;
    }
    private double MalzemeSatisiGelir(String BasTarih,String BitTarih){
      String sql="SELECT * FROM \"MalzemeSatisi\" where satildigi_tarih between '"+BasTarih+"' and '"+BitTarih+"'";
      double toplam=0;
      int row;
      try {
          baglanti=dao.getBaglanti();
          ifade=baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
          sonuc=ifade.executeQuery(sql);
          sonuc.last();
          row=sonuc.getRow();
          sonuc.first();
          
          for(int i=0;i<row;i++){
              
                toplam+=sonuc.getDouble("satildigi_ucret")-MalzemeGelisFiyati(sonuc.getInt("malzeme_id"));
                sonuc.next();
                
                
            }
     
      } catch (Exception e) {
          
      }
      return toplam;
    }
     private double MaasGiderleriHesapla(String BasTarih,String BitTarih){
       String sql="SELECT * FROM \"Personel\" where cikis_tarihi='0'";
       double toplam_maas=0,toplam_sigorta=0,toplam=0;
       int row,kacay=0;
       long fark;
       SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
       Date d1 = null ;
       Date d2 = null ;
      
       try {
           
          baglanti=dao.getBaglanti();
          ifade=baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
          d1 = format.parse(BasTarih);
	  d2 = format.parse(BitTarih); 
          fark = d1.getTime()-d2.getTime();
          if(d2.getYear()-d1.getYear()>0){
              kacay = (int) ((fark / (24 * 60 * 60 * 1000*30))-1);
          }
          else{
              kacay = (int) (fark / (24 * 60 * 60 * 1000*30));
          }
          
          sonuc=ifade.executeQuery(sql);
          sonuc.last();
          row=sonuc.getRow();
          sonuc.first();
        
          for(int i=0;i<row;i++){
                   toplam_maas+=sonuc.getDouble("personel_maas");
                   toplam_sigorta+=sonuc.getDouble("sigorta");
                   sonuc.next();
            }
        toplam=toplam_maas+toplam_sigorta;
      } catch (Exception e) {
          
      }
      return toplam*kacay;
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_bast = new javax.swing.JTextField();
        txt_bitt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaGelir = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaGider = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkar = new javax.swing.JTextField();
        txtZarar = new javax.swing.JTextField();
        btnHesapla = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Belirli Tarihte Gelir Gider Kar Zarar Dökümü");

        jLabel2.setText("Başlangıç Tarihi Giriniz :");

        jLabel3.setText("Bitiş Tarihi Giriniz :");

        txtareaGelir.setColumns(20);
        txtareaGelir.setRows(5);
        jScrollPane1.setViewportView(txtareaGelir);

        jLabel4.setText("Gelir ");

        jLabel5.setText("Gider ");

        txtareaGider.setColumns(20);
        txtareaGider.setRows(5);
        jScrollPane2.setViewportView(txtareaGider);

        jLabel6.setText("Toplam Kar :");

        jLabel7.setText("Toplam Zarar: ");

        btnHesapla.setText("Hesapla");
        btnHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesaplaActionPerformed(evt);
            }
        });

        btn_geri.setText("İşlemlere Dön");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnHesapla)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_bast, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(txt_bitt))))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(txtkar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtZarar)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btn_geri)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_geri))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_bast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_bitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtZarar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHesapla)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        String bast=txt_bast.getText();
        String bitt=txt_bitt.getText();
        String data="";
        String data1="";
        double kar=0;
        
        data="Malzeme Satışından Gelen Gelir: "+MalzemeSatisiGelir(bast,bitt);
        data+="\nÖn Tanımlı İşlerden Gelen Gelir: "+OnTanimliIsGelir(bast,bitt);
        
        txtareaGelir.setText(data);
        data1="Maaş Giderleri :"+MaasGiderleriHesapla(bast,bitt);
        txtareaGider.setText(data1);
        kar=MalzemeSatisiGelir(bast,bitt)-MaasGiderleriHesapla(bast,bitt);
        if(kar<0){
            txtZarar.setText(String.valueOf(kar*(-1)));
        }
        else{
            txtkar.setText(String.valueOf(kar));
        }
        
    }//GEN-LAST:event_btnHesaplaActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        Islemler is=new Islemler();
        is.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BelliTarihteGelirGiderKarZararDokumu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BelliTarihteGelirGiderKarZararDokumu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BelliTarihteGelirGiderKarZararDokumu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BelliTarihteGelirGiderKarZararDokumu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BelliTarihteGelirGiderKarZararDokumu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHesapla;
    private javax.swing.JButton btn_geri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtZarar;
    private javax.swing.JTextField txt_bast;
    private javax.swing.JTextField txt_bitt;
    private javax.swing.JTextArea txtareaGelir;
    private javax.swing.JTextArea txtareaGider;
    private javax.swing.JTextField txtkar;
    // End of variables declaration//GEN-END:variables
}

