/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technicalservicesoftware;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Gizem
 */
public class TeknikServislerArasiIsler extends javax.swing.JFrame {

    /**
     * Creates new form TeknikServislerArasiIslemler
     */
    private Connection baglanti;
    private ResultSet sonuc;
    private Statement ifade;
    private DatabaseAccessObject dao=new DatabaseAccessObject();

    private void verileriGetir(){
        String sql="SELECT * FROM \"TeknikServisArasiIslemler\"";
        try {
            baglanti=dao.getBaglanti();
            ifade=baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            sonuc=ifade.executeQuery(sql);
            sonuc.next();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void verileriGoster(){
        txtBosalt();
        if (sonuc!=null){
            try {
                tf_goncihaz.setText(sonuc.getString("gonderilen_cihaz_id")); 
                tf_gonderen.setText(sonuc.getString("gonderen_servis_id"));
                tf_gonderilen.setText(sonuc.getString("alan_servis_id"));
                tf_gonmalz.setText(sonuc.getString("gonderilen_malzeme_id"));
                tf_gontarih.setText(sonuc.getString("gonderilme_tarihi"));
                tf_kayitno.setText(sonuc.getString("islem_id"));
                tf_teslimtarihi.setText(sonuc.getString("teslim_tarihi"));

            } catch (Exception ex) {
                ex.printStackTrace();
            }
           
            
        }
    }
    
    private void txtBosalt(){
        tf_goncihaz.setText("");
        tf_gonderen.setText("");
        tf_gonderilen.setText("");
        tf_gonmalz.setText("");
        tf_gontarih.setText("");
        tf_kayitno.setText("");
        tf_teslimtarihi.setText("");
        tf_teslimtarihi.requestFocus();
    }
    private void ilk_islemler(){
        tf_gonderen.requestFocus();
        tf_kayitno.setText(String.valueOf(kacinci()+1));
        String DateTime = now("dd-MM-yyy");
        tf_gontarih.setText(DateTime);
        verileriGetir();
    }
   public static String now(String dateFormat) 
    {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
        return sdf.format(cal.getTime());
    }
    /**
     * Creates new form MusteriIslemleri
     */

    public int kacinci(){
            int row=0;
            try {
                baglanti=dao.getBaglanti();
                ifade=baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                sonuc=ifade.executeQuery("SELECT * FROM \"TeknikServisArasiIslemler\"");
                if(sonuc!=null){
                    sonuc.last();
                    row=sonuc.getRow();
                    sonuc.beforeFirst(); //imlec basa alınır
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            return row;
        }
    public TeknikServislerArasiIsler() {
        initComponents();
        ilk_islemler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_kaydet = new javax.swing.JButton();
        tf_gonderen = new javax.swing.JTextField();
        btn_geri = new javax.swing.JButton();
        tf_goncihaz = new javax.swing.JTextField();
        tf_gonmalz = new javax.swing.JTextField();
        tf_gontarih = new javax.swing.JTextField();
        tf_teslimtarihi = new javax.swing.JTextField();
        tf_kayitno = new javax.swing.JTextField();
        btn_sil = new javax.swing.JButton();
        btn_guncelleme = new javax.swing.JButton();
        btn_temizle = new javax.swing.JButton();
        btn_ikayit = new javax.swing.JButton();
        btn_skayit = new javax.swing.JButton();
        btn_okayit = new javax.swing.JButton();
        btn_nkayit = new javax.swing.JButton();
        tf_ara = new javax.swing.JTextField();
        btn_ara = new javax.swing.JButton();
        tf_gonderilen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Teknik Servisler Arası İletişim Bilgileri");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Gönderen Servis Numarası :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gönderilen Servis Numarası :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gönderilen Cihaz Numarası :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Gönderilen Malzeme Numarası :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gönderilme Tarihi :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Teslim Tarihi :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kayıt Numarası :");

        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        btn_geri.setText("İşlemlere Dön");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_guncelleme.setText("Güncelle");
        btn_guncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncellemeActionPerformed(evt);
            }
        });

        btn_temizle.setText("Temizle");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });

        btn_ikayit.setText("İlk Kayıt");
        btn_ikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ikayitActionPerformed(evt);
            }
        });

        btn_skayit.setText("Son Kayıt");
        btn_skayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_skayitActionPerformed(evt);
            }
        });

        btn_okayit.setText("Önceki Kayıt");
        btn_okayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okayitActionPerformed(evt);
            }
        });

        btn_nkayit.setText("Sonraki Kayıt");
        btn_nkayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nkayitActionPerformed(evt);
            }
        });

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btn_geri))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_kaydet)
                                            .addComponent(btn_ikayit))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_skayit)
                                            .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tf_ara))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_okayit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_nkayit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_guncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_kayitno, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_teslimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_gontarih, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_gonmalz, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_goncihaz, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_gonderen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_gonderilen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_geri))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_gonderen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_gonderilen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_goncihaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_gonmalz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_gontarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_teslimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_kayitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kaydet)
                    .addComponent(btn_sil)
                    .addComponent(btn_guncelleme)
                    .addComponent(btn_temizle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ikayit)
                    .addComponent(btn_skayit)
                    .addComponent(btn_okayit)
                    .addComponent(btn_nkayit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ara))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        Islemler islem=new Islemler();
        islem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        int goncihaz=Integer.parseInt(tf_goncihaz.getText());
        int gonderen=Integer.parseInt(tf_gonderen.getText());
        int gonderilen=Integer.parseInt(tf_gonderilen.getText());
        int gonmalz=Integer.parseInt(tf_gonmalz.getText());
        String gontarih=tf_gontarih.getText();
        int kayitno=Integer.parseInt(tf_kayitno.getText());
        String teslimtarihi=tf_teslimtarihi.getText(); 
        try {
            sonuc.moveToInsertRow();
            sonuc.updateString("teslim_tarihi",teslimtarihi);
            sonuc.updateString("gonderilme_tarihi",gontarih);
            sonuc.updateInt("gonderen_servis_id", gonderen);
            sonuc.updateInt("alan_servis_id",gonderilen);
            sonuc.updateInt("gonderilen_cihaz_id",goncihaz);
            sonuc.updateInt("islem_id",kayitno);
            sonuc.updateInt("gonderilen_malzeme_id",gonmalz);
            sonuc.insertRow();
            verileriGetir();
           // verileriGoster();
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        Statement ifade;
        try {
              ifade=baglanti.createStatement();
              String sql="DELETE FROM \"TeknikServisArasiIslemler\""+" WHERE islem_id="+tf_kayitno.getText();
              ifade.executeUpdate(sql);
              verileriGetir();
             // verileriGoster();
            } catch (SQLException ex) {
                ex.printStackTrace();
        }    
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_guncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncellemeActionPerformed
        Statement ifade;
        String goncihaz=tf_goncihaz.getText();
        String gonderen=tf_gonderen.getText();
        String gonderilen=tf_gonderilen.getText();
        String gonmalz=tf_gonmalz.getText();
        int kayitno=Integer.parseInt(tf_kayitno.getText());
        String teslimtarihi=tf_teslimtarihi.getText(); 
               try {
                     ifade=baglanti.createStatement();
                     String sql="UPDATE \"TeknikServisArasiIslemler\" SET "+
                         "teslim_tarihi='"+teslimtarihi+
                         "', gonderen_servis_id='"+gonderen+"'"+
                         ", alan_servis_id="+gonderilen+
                         ", gonderilen_cihaz_id="+goncihaz+
                         ", gonderilen_malzeme_id="+gonmalz+
                         " WHERE islem_id="+kayitno;
                     ifade.executeUpdate(sql);
                     verileriGetir();
                     verileriGoster();
                   } catch (Exception ex) {
                       ex.printStackTrace();
               } 
        
    }//GEN-LAST:event_btn_guncellemeActionPerformed

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed
        txtBosalt();
        ilk_islemler();
    }//GEN-LAST:event_btn_temizleActionPerformed

    private void btn_ikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ikayitActionPerformed
        try {
            sonuc.first();
            verileriGoster();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_ikayitActionPerformed

    private void btn_skayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_skayitActionPerformed
         try {
            sonuc.last();
            verileriGoster();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_skayitActionPerformed

    private void btn_okayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okayitActionPerformed
        try {
            if(sonuc.previous()){
                if(sonuc.isBeforeFirst()){
                    sonuc.next();
                }
                verileriGoster();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }    }//GEN-LAST:event_btn_okayitActionPerformed

    private void btn_nkayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nkayitActionPerformed
        try {
            if(sonuc.next()){
                if(sonuc.isAfterLast()){
                    sonuc.last();
                }
                verileriGoster();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }    
    }//GEN-LAST:event_btn_nkayitActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        int  id=Integer.parseInt(tf_kayitno.getText());
        try {
            int mevcut_satir=sonuc.getRow();
            sonuc.first();
            sonuc.previous();
            int row=0;
            boolean bulundu=false;
            while(sonuc.next()){
                row++;
                if(sonuc.getInt("islem_id")==id){
                    bulundu=true;
                    break;
                } 
            }
            if(bulundu){
                sonuc.absolute(row);
                }
            else{
                sonuc.absolute(mevcut_satir);
                       
                }
             verileriGoster();
        }
            catch (SQLException ex) {
        }    
    }//GEN-LAST:event_btn_araActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeknikServislerArasiIsler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeknikServislerArasiIsler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeknikServislerArasiIsler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeknikServislerArasiIsler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeknikServislerArasiIsler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_guncelleme;
    private javax.swing.JButton btn_ikayit;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_nkayit;
    private javax.swing.JButton btn_okayit;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_skayit;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_ara;
    private javax.swing.JTextField tf_goncihaz;
    private javax.swing.JTextField tf_gonderen;
    private javax.swing.JTextField tf_gonderilen;
    private javax.swing.JTextField tf_gonmalz;
    private javax.swing.JTextField tf_gontarih;
    private javax.swing.JTextField tf_kayitno;
    private javax.swing.JTextField tf_teslimtarihi;
    // End of variables declaration//GEN-END:variables
}
